# -----------------------------------------------------------------------------------------
# This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
#
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Lesser General Public License for more details.
#
# This file should not be modified generally.
#
# Copyright (c) 2015-2016, linnvv_0011@163.com  All rights reserved.
# -----------------------------------------------------------------------------------------

project_root ?= ..
media_mux_mod_lib_name := muxer

include $(project_root)/makefile_head.mk

media_mux_mod_cpp_flags += $(media_mux_tool_chain_cpp_flags)

include makefile_sources.mk
include $(project_root)/makefile_post.mk